name: Download adblock source list

on:
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: adblock
        run: |
          echo "Downloading easylist_adservers block list..."
          curl -s https://github.com/easylist/easylist/blob/master/easylist/easylist_adservers.txt -o filter.txt
          grep -o -P '(?<=^\|\|).*(?=\^$)' filter.txt | grep -v '\*' > easylist_adservers.yaml
          sed -ie '/^#/! s/^/  - DOMAIN,/' easylist_adservers.yaml
          sed -i '1i payload:' easylist_adservers.yaml
          rm -fr easylist_adservers.yamle filter.txte filter.txt

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
